 	01. COMMISSION.py 	
	02. CONCENTRIC_CIRCLES.py 	
	03. Gross_pay.py 	
	04. Infinite.py 	
	05. Property_tax.py 	
	06. Rectangular_pattern.py 	
	07. Retail_no_validation.py 	
	08. Retail_with_validation.py 	
	09. Simple_loop1.py 	
	10. Simple_loop2.py 	
	11. Simple_loop3.py 	
	12. Simple_loop4.py 	
	13. Speed_converter.py 	
	14. Spiral_circles.py 	
	15. Spiral_lines.py 	
	16. Squares.py 	
	17. Stair_step_pattern.py 	
	18. Sum_numbers.py 	
	19. Temperature.py 	
	20. Test_score_averages.py 	
	21. Triangle_pattern.py 	
	22. User_squares1.py 	
	23. User_squares2.py
